---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: diffing
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: diffing-server
    spec:
      containers:
      - name: processing
        image: envirodgi/processing:latest
        imagePullPolicy: Never
        ports:
        - name: diffing
          containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: processing-secrets
              key: sentry_dsn
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: WEB_MONITORING_DB_URL
          value: "http://$(MY_POD_IP):30000/"
        - name: WEB_MONITORING_DB_EMAIL
          value: seed-admin@example.com
        - name: WEB_MONITORING_DB_PASSWORD
          value: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: diffing
  namespace: development
spec:
  selector:
    app: diffing-server
  ports:
  - name: http
    protocol: TCP
    port: 4000 
    targetPort: diffing
    nodePort: 30004
  type: NodePort
