---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui 
        image: envirodgi/ui:latest
        imagePullPolicy: Never
        ports: 
        - name: ui
          containerPort: 3001
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 5
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: FORCE_SSL
          value: "false"
        - name: GOOGLE_DICTIONARY_SHEET_ID
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key: google_dictionary_sheet_id
        - name: GOOGLE_IMPORTANT_CHANGE_SHEET_ID
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key: google_important_change_sheet_id
        - name: GOOGLE_SERVICE_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key: google_service_client_email
        - name: GOOGLE_SHEETS_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key: google_sheets_private_key
        - name: GOOGLE_TASK_SHEET_ID
          valueFrom:
            secretKeyRef:
              name: ui-secrets
              key:  google_task_sheet_id
        - name: WEB_MONITORING_DB_URL
          value: "http://$(MY_POD_IP):30000/"
        - name: INCREMENTAL_UPDATE
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: development
spec:
  selector:
    app: ui
  ports:
  - name: http
    port: 3001
    targetPort: ui
    nodePort: 30001
  type: NodePort
